apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: pitstop-configmap
resources:

  - rabbitmq-depl.yaml

  - customer-database-depl.yaml

  - pitstop-customer-depl.yaml

  - pitstop-gateway-depl.yaml

  - pitstop-vehicle-depl.yaml

  - vehicle-database-depl.yaml

  - workshop-database-depl.yaml
